# Generated by Django 2.1.3 on 2018-11-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0002_auto_20181111_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
