# Generated by Django 2.1.3 on 2018-11-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0003_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitereport.UsState'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_end',
            field=models.DateField(default=None, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_start',
            field=models.DateField(default=None, null=True, verbose_name='date started'),
        ),
    ]
